### ISSUE TITLE
expose DLNA ports of jellyfin

### ISSUE THREAD

**Issue by christf** [brianmcarey/jellyfin-helm#6]
It would be great if the DLNA feature would be enabled as described 
https://www.jamesmoriarty.xyz/post/kubernetes-and-dlna/

**Comment by christf** [comment]
I still cannot see jellyfin, even with the deploymentconfig exposing udp port 1900.
It looks something like this is needed: https://serverfault.com/questions/934581/configuring-kubernetes-service-as-a-upnp-device

adjustments in the service.
I tried with:

```
@@ -47,6 +47,13 @@ spec:
 {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
       nodePort: {{.Values.service.nodePort}}
 {{ end }}
+        {{ if .Values.enableDLNA }}
+    - name: dlnha
+      port: 1900
+      protocol: UDP
+      targetPort: 1900
+      nodePort: {{.Values.service.nodePort}}
+{{- end }}
   selector:
     app.kubernetes.io/name: {{ include "jellyfin.name" . }}
     app.kubernetes.io/instance: {{ .Release.Name }}

```

and I can now see other dlna renderers on my lan from jellyfin. In my dlna controller howerver I still cannot see jellyfin so while the above helps already, there is more to be done to solve this.

**Comment by brianmcarey** [comment]
Closing this as archiving this repository
